### ISSUE TITLE
Ringtones Player?

### ISSUE THREAD

**Issue by Andrious** [imedboumalek/flutter_system_ringtones#1]
I noted the player you have commented out. Is there such a player? 
I can't seem to readily find one that reads an url as represented in your library here.
![image](https://user-images.githubusercontent.com/32497443/201008542-bf21b099-a9e0-42bf-824a-a1364e940e7b.png)

**Comment by imedboumalek** [comment]
Thanks for creating the first issue :) 

no ringtone player, I was experimenting with another plugin to see if it's playable. Since people have actually started using this plugin, I'll invest more time into it. :)

**Comment by bahman2000** [comment]
You can use this package: [https://pub.dev/packages/just_audio](url)
```dart
final player = AudioPlayer();
player.setAudioSource(AudioSource.uri(Uri.parse(ringtones[index].uri)));
player.play();
```

**Comment by Andrious** [comment]
Excellent, Bahman.  I'll do that. Thanks.
